apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "oldmanmilliner.chart" . }}-{{ .Release.Name }}
  labels:
    app: {{ template "oldmanmilliner.chart" . }}
    chart: {{ template "oldmanmilliner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "oldmanmilliner.chart" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "oldmanmilliner.chart" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ template "oldmanmilliner.name" . }} 
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - mountPath: /var/www/html/
            name: site-data
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: site-data
        configMap:
          Name: html-files
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
