apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  annotations: {}
spec:
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /var/www/html
            backend:
              serviceName: {{ .Chart.Name }}-{{ .Release.Name }}
              servicePort: 80
  {{- end }}
