apiVersion: v1
kind: Service
metadata:
  name: {{ template "oldmanmilliner.chart" . }}-{{ .Release.Name }}

spec:
  ports:
      name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ template "oldmanmilliner.chart" . }}-{{ .Release.Name }}
