apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "oldmanmilliner.name" . }}
    chart: {{ template "oldmanmilliner.chart" . }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.service.name }}
      port: 80
  selector:
    app: {{ template "oldmanmilliner.name" . }}
