apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}


spec:
  ports:
      name:http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.service.name }}-{{ .Release.Name }}