apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.service.name }}
    chart: {{ template "oldmanmilliner.chart" . }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.service.name }}
      port: 80
  selector:
    app: {{ .Values.service.name }}
