pipeline {
  agent any
  stages {
    stage('test') {
      steps {
        sh """
          /usr/local/bin/helm lint --values=helm/artsncrafts/values.yaml helm/artsncrafts/
        """
      }
    }
    stage('helm dry run'){
      steps {
        sh """
          helm init helm/artsncrafts -n dev
        """
      }
    }
  }
}