
pipeline {
    agent {
        kubernetes {
            label 'helm-slave'
            containerTemplate {
                name 'docker pull dtzar/helm-kubectl'
                image 'docker.io/dtzar/helm-kubectl:latest'
                command 'which helm'
            }
        }
    }
  stages {
    stage('test') {
      steps {
        sh """
          export PATH=/usr/local/bin:$PATH
          which helm
          helm lint --values=helm/artsncrafts/values.yaml helm/artsncrafts/
        """
      }
    }
    stage('helm dry run'){
      steps {
        sh """
          export PATH=/usr/local/bin:$PATH
          echo $PATH
          which helm
          helm init helm/artsncrafts -n dev 
        """
      }
    }
  }
}