
pipeline {
  agent {
    label 'helm-slave'
  }
  stages {


    stage('helm init') {
      steps {
        sh """
          helm lint helm/artsncrafts/
        """
      }
    }
    stage('helm dry run'){
      steps {
        sh """
          helm install helm/artsncrafts/ --dry-run --debug 
        """
      }
    }
    stage('helm deploy'){
      steps {
        sh """
          helm install helm/artsncrafts/ --namespace dev --debug
        """
      }
    }
  }
}