apiVersion: v1
kind: Service
metadata:
  name: {{ template "artsncrafts.fullname" . }}
  labels:
    app: {{ template "artsncrafts.name" . }}
    chart: {{ template "artsncrafts.chart" . }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
  selector:
    app: {{ template "artsncrafts.name" . }}
